---
title: "Candor Analytics Overview"
author: Joey Bellerose & Mike McHenry
date: January 12, 2019
output: html_notebook
---

# What Is Our Purpose?
<h2>Hello</h2>

- To extract truth from data to generate the answers decision makers need to move forward

- What could we accomplish if we had the right answers to the right questions?

# How We Extract Truth?

- Build in Transparency at all levels

  - Create clarity, accuracy and understanding

- Data needs to be the foundation

  - A proper foundation allows understanding of context

# What Do We Offer?

- Cleaning - Making large/unstructured/messy data usable

- Discovery - Learning about the past by letting the data speak for itself

- Modeling - Simulating scenarios for real-time results to proactively get ahead of the curve

- Forecasting - Seeing where your trends are taking you

- Interpretation - Understanding what the results mean

- Visualization - Composing static/interactive graphics that tell compelling stories

- Communication - Providing actionable insights that show a clear path forward

# How Do Others Benefit

- Automated analysis/reporting

- Real-time results

- Recommendations on path forward

# Examples

## Mike's Test Automation

## Joey's Contract Analysis

# What Is The Path Forward?

- Incubating under existing Prime

  - Combine Prime's domain expertise with our analytical understanding
  
- Would you be interested in collaborating with us?
