---
title: "Candor Analytics Overview"
author: Joey Bellerose & Mike McHenry
date: January 12, 2019
output: revealjs::revealjs_presentation
---

## What Is Our Purpose?

- To extract truth from data to generate the answers decision makers need to move forward

- What could we accomplish if we had the right answers to the right questions?


## How We Extract Truth?

- Build in Transparency at all levels

- Data needs to be the foundation

<aside class="notes">
- Create clarity, accuracy and understanding
- A proper foundation allows understanding of context
</aside>

  

## What Do We Offer?

- Cleaning - Making large/unstructured/messy data usable

- Discovery - Learning about the past by letting the data speak for itself

- Modeling - Simulating scenarios for real-time results to proactively get ahead of the curve

- Forecasting - Seeing where your trends are taking you

- Interpretation - Understanding what the results mean

- Visualization - Composing static/interactive graphics that tell compelling stories

- Communication - Providing actionable insights that show a clear path forward

## How Do Others Benefit?

- Automated analysis/reporting

- Real-time results

- Recommendations on path forward

## Example
<video width="100%" height="600" controls id="video">
<source src="Stock App 2018.07.24.mp4" type="video/mp4" >
</video>

<a href = "https://bellerosejoey.shinyapps.io/StockApp/">Stock Application</a>




## What Is The Path Forward?

- Incubating under existing Prime

  - Combine Prime's domain expertise with our analytical understanding
  
- Would you be interested in collaborating with us?

<script>
document.querySelector('video').playbackRate = 0.5
</script>